version: "2"
linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - gochecknoinits
    - gocognit
    # - goconst
    - gocritic
    - gocyclo
    - gosec
    - importas
    - misspell
    - nakedret
    - nestif
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - sloppyReassign
        - whyNoLint
      enabled-tags:
        - experimental
        - opinionated
    govet:
      enable:
        - shadow
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - ".*\\.gen\\.go$"
formatters:
  enable:
    - gofmt
    - goimports
