dir: "{{.InterfaceDir}}"
filename: "mock_{{ .InterfaceName | snakecase }}.gen.go"
pkgname: '{{.SrcPackageName}}'
structname: '{{.Mock}}{{.InterfaceName}}'
template: testify
packages:
  github.com/liebeSonne/gophkeeper/internal/server/service:
    interfaces:
      UserRepository: { }
      TokenRepository: { }
      DataRepository: { }
      FileRepository: { }
  github.com/liebeSonne/gophkeeper/internal/server/auth:
    interfaces:
      Service: { }
  github.com/liebeSonne/gophkeeper/internal/logger:
    interfaces:
      Logger: { }
  github.com/liebeSonne/gophkeeper/internal/server/handler:
    interfaces:
      AuthService: { }
      DataService: { }
      FileService: { }
  github.com/liebeSonne/gophkeeper/internal/crypto:
    interfaces:
      Encryptor: { }
  github.com/liebeSonne/gophkeeper/internal/storage:
    interfaces:
      MinIOClient: { }