FROM golang:1.26-alpine AS builder

RUN apk --no-cache add git ca-certificates

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG VERSION=dev
ARG DATE=unknown
ARG COMMIT=unknown

RUN CGO_ENABLED=0 go build \
    -ldflags="-s -w -X github.com/liebeSonne/gophkeeper/cmd/client.version=${VERSION} -X github.com/liebeSonne/gophkeeper/cmd/client.buildDate=${DATE} -X github.com/liebeSonne/gophkeeper/cmd/client.commit=${COMMIT}" \
    -o /gophkeeper-client ./cmd/client

FROM alpine:3.20

RUN apk --no-cache add ca-certificates

RUN addgroup -S gophkeeper && adduser -S gophkeeper -G gophkeeper

COPY --from=builder /gophkeeper-client /usr/local/bin/

USER gophkeeper

ENTRYPOINT ["gophkeeper-client"]
