// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetUserIDFromToken provides a mock function for the type MockService
func (_mock *MockService) GetUserIDFromToken(tokenString string) (uuid.UUID, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for GetUserIDFromToken")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (uuid.UUID, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) uuid.UUID); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetUserIDFromToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserIDFromToken'
type MockService_GetUserIDFromToken_Call struct {
	*mock.Call
}

// GetUserIDFromToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockService_Expecter) GetUserIDFromToken(tokenString interface{}) *MockService_GetUserIDFromToken_Call {
	return &MockService_GetUserIDFromToken_Call{Call: _e.mock.On("GetUserIDFromToken", tokenString)}
}

func (_c *MockService_GetUserIDFromToken_Call) Run(run func(tokenString string)) *MockService_GetUserIDFromToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetUserIDFromToken_Call) Return(uUID uuid.UUID, err error) *MockService_GetUserIDFromToken_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockService_GetUserIDFromToken_Call) RunAndReturn(run func(tokenString string) (uuid.UUID, error)) *MockService_GetUserIDFromToken_Call {
	_c.Call.Return(run)
	return _c
}
