// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMinIOClient creates a new instance of MockMinIOClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMinIOClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMinIOClient {
	mock := &MockMinIOClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMinIOClient is an autogenerated mock type for the MinIOClient type
type MockMinIOClient struct {
	mock.Mock
}

type MockMinIOClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMinIOClient) EXPECT() *MockMinIOClient_Expecter {
	return &MockMinIOClient_Expecter{mock: &_m.Mock}
}

// DeleteObject provides a mock function for the type MockMinIOClient
func (_mock *MockMinIOClient) DeleteObject(ctx context.Context, bucket string, objectKey string) error {
	ret := _mock.Called(ctx, bucket, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, bucket, objectKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMinIOClient_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type MockMinIOClient_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - objectKey string
func (_e *MockMinIOClient_Expecter) DeleteObject(ctx interface{}, bucket interface{}, objectKey interface{}) *MockMinIOClient_DeleteObject_Call {
	return &MockMinIOClient_DeleteObject_Call{Call: _e.mock.On("DeleteObject", ctx, bucket, objectKey)}
}

func (_c *MockMinIOClient_DeleteObject_Call) Run(run func(ctx context.Context, bucket string, objectKey string)) *MockMinIOClient_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMinIOClient_DeleteObject_Call) Return(err error) *MockMinIOClient_DeleteObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMinIOClient_DeleteObject_Call) RunAndReturn(run func(ctx context.Context, bucket string, objectKey string) error) *MockMinIOClient_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObjects provides a mock function for the type MockMinIOClient
func (_mock *MockMinIOClient) DeleteObjects(ctx context.Context, bucket string, objectKeys []string) error {
	ret := _mock.Called(ctx, bucket, objectKeys)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObjects")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(ctx, bucket, objectKeys)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMinIOClient_DeleteObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObjects'
type MockMinIOClient_DeleteObjects_Call struct {
	*mock.Call
}

// DeleteObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - objectKeys []string
func (_e *MockMinIOClient_Expecter) DeleteObjects(ctx interface{}, bucket interface{}, objectKeys interface{}) *MockMinIOClient_DeleteObjects_Call {
	return &MockMinIOClient_DeleteObjects_Call{Call: _e.mock.On("DeleteObjects", ctx, bucket, objectKeys)}
}

func (_c *MockMinIOClient_DeleteObjects_Call) Run(run func(ctx context.Context, bucket string, objectKeys []string)) *MockMinIOClient_DeleteObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMinIOClient_DeleteObjects_Call) Return(err error) *MockMinIOClient_DeleteObjects_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMinIOClient_DeleteObjects_Call) RunAndReturn(run func(ctx context.Context, bucket string, objectKeys []string) error) *MockMinIOClient_DeleteObjects_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureBucket provides a mock function for the type MockMinIOClient
func (_mock *MockMinIOClient) EnsureBucket(ctx context.Context, bucketName string) error {
	ret := _mock.Called(ctx, bucketName)

	if len(ret) == 0 {
		panic("no return value specified for EnsureBucket")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, bucketName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMinIOClient_EnsureBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureBucket'
type MockMinIOClient_EnsureBucket_Call struct {
	*mock.Call
}

// EnsureBucket is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketName string
func (_e *MockMinIOClient_Expecter) EnsureBucket(ctx interface{}, bucketName interface{}) *MockMinIOClient_EnsureBucket_Call {
	return &MockMinIOClient_EnsureBucket_Call{Call: _e.mock.On("EnsureBucket", ctx, bucketName)}
}

func (_c *MockMinIOClient_EnsureBucket_Call) Run(run func(ctx context.Context, bucketName string)) *MockMinIOClient_EnsureBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMinIOClient_EnsureBucket_Call) Return(err error) *MockMinIOClient_EnsureBucket_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMinIOClient_EnsureBucket_Call) RunAndReturn(run func(ctx context.Context, bucketName string) error) *MockMinIOClient_EnsureBucket_Call {
	_c.Call.Return(run)
	return _c
}

// GetObject provides a mock function for the type MockMinIOClient
func (_mock *MockMinIOClient) GetObject(ctx context.Context, bucket string, objectKey string) (io.ReadCloser, int64, error) {
	ret := _mock.Called(ctx, bucket, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 io.ReadCloser
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (io.ReadCloser, int64, error)); ok {
		return returnFunc(ctx, bucket, objectKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, bucket, objectKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) int64); ok {
		r1 = returnFunc(ctx, bucket, objectKey)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, bucket, objectKey)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMinIOClient_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type MockMinIOClient_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - objectKey string
func (_e *MockMinIOClient_Expecter) GetObject(ctx interface{}, bucket interface{}, objectKey interface{}) *MockMinIOClient_GetObject_Call {
	return &MockMinIOClient_GetObject_Call{Call: _e.mock.On("GetObject", ctx, bucket, objectKey)}
}

func (_c *MockMinIOClient_GetObject_Call) Run(run func(ctx context.Context, bucket string, objectKey string)) *MockMinIOClient_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMinIOClient_GetObject_Call) Return(reader io.ReadCloser, size int64, err error) *MockMinIOClient_GetObject_Call {
	_c.Call.Return(reader, size, err)
	return _c
}

func (_c *MockMinIOClient_GetObject_Call) RunAndReturn(run func(ctx context.Context, bucket string, objectKey string) (io.ReadCloser, int64, error)) *MockMinIOClient_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// PutObject provides a mock function for the type MockMinIOClient
func (_mock *MockMinIOClient) PutObject(ctx context.Context, bucket string, objectKey string, reader io.Reader, size int64) error {
	ret := _mock.Called(ctx, bucket, objectKey, reader, size)

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, int64) error); ok {
		r0 = returnFunc(ctx, bucket, objectKey, reader, size)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMinIOClient_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type MockMinIOClient_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - objectKey string
//   - reader io.Reader
//   - size int64
func (_e *MockMinIOClient_Expecter) PutObject(ctx interface{}, bucket interface{}, objectKey interface{}, reader interface{}, size interface{}) *MockMinIOClient_PutObject_Call {
	return &MockMinIOClient_PutObject_Call{Call: _e.mock.On("PutObject", ctx, bucket, objectKey, reader, size)}
}

func (_c *MockMinIOClient_PutObject_Call) Run(run func(ctx context.Context, bucket string, objectKey string, reader io.Reader, size int64)) *MockMinIOClient_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockMinIOClient_PutObject_Call) Return(err error) *MockMinIOClient_PutObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMinIOClient_PutObject_Call) RunAndReturn(run func(ctx context.Context, bucket string, objectKey string, reader io.Reader, size int64) error) *MockMinIOClient_PutObject_Call {
	_c.Call.Return(run)
	return _c
}
