// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/google/uuid"
	"github.com/liebeSonne/gophkeeper/internal/model"
	"github.com/liebeSonne/gophkeeper/internal/repository/db"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDataRepository creates a new instance of MockDataRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDataRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDataRepository {
	mock := &MockDataRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDataRepository is an autogenerated mock type for the DataRepository type
type MockDataRepository struct {
	mock.Mock
}

type MockDataRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDataRepository) EXPECT() *MockDataRepository_Expecter {
	return &MockDataRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockDataRepository
func (_mock *MockDataRepository) Count(ctx context.Context, spec db.ListSpec) (int, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListSpec) (int, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListSpec) int); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockDataRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - spec db.ListSpec
func (_e *MockDataRepository_Expecter) Count(ctx interface{}, spec interface{}) *MockDataRepository_Count_Call {
	return &MockDataRepository_Count_Call{Call: _e.mock.On("Count", ctx, spec)}
}

func (_c *MockDataRepository_Count_Call) Run(run func(ctx context.Context, spec db.ListSpec)) *MockDataRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListSpec
		if args[1] != nil {
			arg1 = args[1].(db.ListSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataRepository_Count_Call) Return(n int, err error) *MockDataRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockDataRepository_Count_Call) RunAndReturn(run func(ctx context.Context, spec db.ListSpec) (int, error)) *MockDataRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockDataRepository
func (_mock *MockDataRepository) Delete(ctx context.Context, ids []uuid.UUID) error {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDataRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDataRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockDataRepository_Expecter) Delete(ctx interface{}, ids interface{}) *MockDataRepository_Delete_Call {
	return &MockDataRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ids)}
}

func (_c *MockDataRepository_Delete_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockDataRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataRepository_Delete_Call) Return(err error) *MockDataRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDataRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) error) *MockDataRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockDataRepository
func (_mock *MockDataRepository) GetByID(ctx context.Context, id uuid.UUID) (model.Data, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Data
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Data, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Data); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Data)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockDataRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDataRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockDataRepository_GetByID_Call {
	return &MockDataRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockDataRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDataRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataRepository_GetByID_Call) Return(data model.Data, err error) *MockDataRepository_GetByID_Call {
	_c.Call.Return(data, err)
	return _c
}

func (_c *MockDataRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (model.Data, error)) *MockDataRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockDataRepository
func (_mock *MockDataRepository) List(ctx context.Context, spec db.ListSpec) ([]model.Data, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Data
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListSpec) ([]model.Data, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListSpec) []model.Data); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Data)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDataRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - spec db.ListSpec
func (_e *MockDataRepository_Expecter) List(ctx interface{}, spec interface{}) *MockDataRepository_List_Call {
	return &MockDataRepository_List_Call{Call: _e.mock.On("List", ctx, spec)}
}

func (_c *MockDataRepository_List_Call) Run(run func(ctx context.Context, spec db.ListSpec)) *MockDataRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListSpec
		if args[1] != nil {
			arg1 = args[1].(db.ListSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataRepository_List_Call) Return(datas []model.Data, err error) *MockDataRepository_List_Call {
	_c.Call.Return(datas, err)
	return _c
}

func (_c *MockDataRepository_List_Call) RunAndReturn(run func(ctx context.Context, spec db.ListSpec) ([]model.Data, error)) *MockDataRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NextID provides a mock function for the type MockDataRepository
func (_mock *MockDataRepository) NextID(ctx context.Context) uuid.UUID {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NextID")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func(context.Context) uuid.UUID); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// MockDataRepository_NextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextID'
type MockDataRepository_NextID_Call struct {
	*mock.Call
}

// NextID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDataRepository_Expecter) NextID(ctx interface{}) *MockDataRepository_NextID_Call {
	return &MockDataRepository_NextID_Call{Call: _e.mock.On("NextID", ctx)}
}

func (_c *MockDataRepository_NextID_Call) Run(run func(ctx context.Context)) *MockDataRepository_NextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDataRepository_NextID_Call) Return(uUID uuid.UUID) *MockDataRepository_NextID_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *MockDataRepository_NextID_Call) RunAndReturn(run func(ctx context.Context) uuid.UUID) *MockDataRepository_NextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type MockDataRepository
func (_mock *MockDataRepository) Store(ctx context.Context, data model.Data) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Data) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDataRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockDataRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - data model.Data
func (_e *MockDataRepository_Expecter) Store(ctx interface{}, data interface{}) *MockDataRepository_Store_Call {
	return &MockDataRepository_Store_Call{Call: _e.mock.On("Store", ctx, data)}
}

func (_c *MockDataRepository_Store_Call) Run(run func(ctx context.Context, data model.Data)) *MockDataRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Data
		if args[1] != nil {
			arg1 = args[1].(model.Data)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataRepository_Store_Call) Return(err error) *MockDataRepository_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDataRepository_Store_Call) RunAndReturn(run func(ctx context.Context, data model.Data) error) *MockDataRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}
