// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/google/uuid"
	"github.com/liebeSonne/gophkeeper/internal/server/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenRepository creates a new instance of MockTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepository {
	mock := &MockTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenRepository is an autogenerated mock type for the TokenRepository type
type MockTokenRepository struct {
	mock.Mock
}

type MockTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepository) EXPECT() *MockTokenRepository_Expecter {
	return &MockTokenRepository_Expecter{mock: &_m.Mock}
}

// GetByTokenHash provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) GetByTokenHash(ctx context.Context, tokenHash string) (model.RefreshToken, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByTokenHash")
	}

	var r0 model.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.RefreshToken, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.RefreshToken); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(model.RefreshToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenRepository_GetByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTokenHash'
type MockTokenRepository_GetByTokenHash_Call struct {
	*mock.Call
}

// GetByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockTokenRepository_Expecter) GetByTokenHash(ctx interface{}, tokenHash interface{}) *MockTokenRepository_GetByTokenHash_Call {
	return &MockTokenRepository_GetByTokenHash_Call{Call: _e.mock.On("GetByTokenHash", ctx, tokenHash)}
}

func (_c *MockTokenRepository_GetByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockTokenRepository_GetByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_GetByTokenHash_Call) Return(refreshToken model.RefreshToken, err error) *MockTokenRepository_GetByTokenHash_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockTokenRepository_GetByTokenHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (model.RefreshToken, error)) *MockTokenRepository_GetByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// NextID provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) NextID(ctx context.Context) uuid.UUID {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NextID")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func(context.Context) uuid.UUID); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// MockTokenRepository_NextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextID'
type MockTokenRepository_NextID_Call struct {
	*mock.Call
}

// NextID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTokenRepository_Expecter) NextID(ctx interface{}) *MockTokenRepository_NextID_Call {
	return &MockTokenRepository_NextID_Call{Call: _e.mock.On("NextID", ctx)}
}

func (_c *MockTokenRepository_NextID_Call) Run(run func(ctx context.Context)) *MockTokenRepository_NextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenRepository_NextID_Call) Return(uUID uuid.UUID) *MockTokenRepository_NextID_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *MockTokenRepository_NextID_Call) RunAndReturn(run func(ctx context.Context) uuid.UUID) *MockTokenRepository_NextID_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) Revoke(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockTokenRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTokenRepository_Expecter) Revoke(ctx interface{}, id interface{}) *MockTokenRepository_Revoke_Call {
	return &MockTokenRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id)}
}

func (_c *MockTokenRepository_Revoke_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTokenRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_Revoke_Call) Return(err error) *MockTokenRepository_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_Revoke_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockTokenRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) Store(ctx context.Context, token model.RefreshToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.RefreshToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockTokenRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - token model.RefreshToken
func (_e *MockTokenRepository_Expecter) Store(ctx interface{}, token interface{}) *MockTokenRepository_Store_Call {
	return &MockTokenRepository_Store_Call{Call: _e.mock.On("Store", ctx, token)}
}

func (_c *MockTokenRepository_Store_Call) Run(run func(ctx context.Context, token model.RefreshToken)) *MockTokenRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(model.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_Store_Call) Return(err error) *MockTokenRepository_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_Store_Call) RunAndReturn(run func(ctx context.Context, token model.RefreshToken) error) *MockTokenRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}
