// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileProvider creates a new instance of MockFileProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileProvider {
	mock := &MockFileProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileProvider is an autogenerated mock type for the FileProvider type
type MockFileProvider struct {
	mock.Mock
}

type MockFileProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileProvider) EXPECT() *MockFileProvider_Expecter {
	return &MockFileProvider_Expecter{mock: &_m.Mock}
}

// GetExistingFilesByUserID provides a mock function for the type MockFileProvider
func (_mock *MockFileProvider) GetExistingFilesByUserID(ctx context.Context, userID uuid.UUID, fileIDs []uuid.UUID) ([]uuid.UUID, error) {
	ret := _mock.Called(ctx, userID, fileIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetExistingFilesByUserID")
	}

	var r0 []uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID) ([]uuid.UUID, error)); ok {
		return returnFunc(ctx, userID, fileIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID) []uuid.UUID); ok {
		r0 = returnFunc(ctx, userID, fileIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, fileIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileProvider_GetExistingFilesByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExistingFilesByUserID'
type MockFileProvider_GetExistingFilesByUserID_Call struct {
	*mock.Call
}

// GetExistingFilesByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - fileIDs []uuid.UUID
func (_e *MockFileProvider_Expecter) GetExistingFilesByUserID(ctx interface{}, userID interface{}, fileIDs interface{}) *MockFileProvider_GetExistingFilesByUserID_Call {
	return &MockFileProvider_GetExistingFilesByUserID_Call{Call: _e.mock.On("GetExistingFilesByUserID", ctx, userID, fileIDs)}
}

func (_c *MockFileProvider_GetExistingFilesByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID, fileIDs []uuid.UUID)) *MockFileProvider_GetExistingFilesByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []uuid.UUID
		if args[2] != nil {
			arg2 = args[2].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileProvider_GetExistingFilesByUserID_Call) Return(uUIDs []uuid.UUID, err error) *MockFileProvider_GetExistingFilesByUserID_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *MockFileProvider_GetExistingFilesByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, fileIDs []uuid.UUID) ([]uuid.UUID, error)) *MockFileProvider_GetExistingFilesByUserID_Call {
	_c.Call.Return(run)
	return _c
}
