// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/google/uuid"
	"github.com/liebeSonne/gophkeeper/internal/server/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// GetByLogin provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetByLogin(ctx context.Context, login string) (model.User, error) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetByLogin")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.User, error)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = returnFunc(ctx, login)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLogin'
type MockUserRepository_GetByLogin_Call struct {
	*mock.Call
}

// GetByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockUserRepository_Expecter) GetByLogin(ctx interface{}, login interface{}) *MockUserRepository_GetByLogin_Call {
	return &MockUserRepository_GetByLogin_Call{Call: _e.mock.On("GetByLogin", ctx, login)}
}

func (_c *MockUserRepository_GetByLogin_Call) Run(run func(ctx context.Context, login string)) *MockUserRepository_GetByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetByLogin_Call) Return(user model.User, err error) *MockUserRepository_GetByLogin_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetByLogin_Call) RunAndReturn(run func(ctx context.Context, login string) (model.User, error)) *MockUserRepository_GetByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// NextID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) NextID(ctx context.Context) uuid.UUID {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NextID")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func(context.Context) uuid.UUID); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// MockUserRepository_NextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextID'
type MockUserRepository_NextID_Call struct {
	*mock.Call
}

// NextID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserRepository_Expecter) NextID(ctx interface{}) *MockUserRepository_NextID_Call {
	return &MockUserRepository_NextID_Call{Call: _e.mock.On("NextID", ctx)}
}

func (_c *MockUserRepository_NextID_Call) Run(run func(ctx context.Context)) *MockUserRepository_NextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_NextID_Call) Return(uUID uuid.UUID) *MockUserRepository_NextID_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *MockUserRepository_NextID_Call) RunAndReturn(run func(ctx context.Context) uuid.UUID) *MockUserRepository_NextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Store(ctx context.Context, user model.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockUserRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
func (_e *MockUserRepository_Expecter) Store(ctx interface{}, user interface{}) *MockUserRepository_Store_Call {
	return &MockUserRepository_Store_Call{Call: _e.mock.On("Store", ctx, user)}
}

func (_c *MockUserRepository_Store_Call) Run(run func(ctx context.Context, user model.User)) *MockUserRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.User
		if args[1] != nil {
			arg1 = args[1].(model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Store_Call) Return(err error) *MockUserRepository_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_Store_Call) RunAndReturn(run func(ctx context.Context, user model.User) error) *MockUserRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}
