// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/google/uuid"
	"github.com/liebeSonne/gophkeeper/internal/server/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileRepository creates a new instance of MockFileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileRepository {
	mock := &MockFileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileRepository is an autogenerated mock type for the FileRepository type
type MockFileRepository struct {
	mock.Mock
}

type MockFileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileRepository) EXPECT() *MockFileRepository_Expecter {
	return &MockFileRepository_Expecter{mock: &_m.Mock}
}

// CountByUserID provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) CountByUserID(ctx context.Context, userID uuid.UUID, query *string) (int, error) {
	ret := _mock.Called(ctx, userID, query)

	if len(ret) == 0 {
		panic("no return value specified for CountByUserID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string) (int, error)); ok {
		return returnFunc(ctx, userID, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string) int); ok {
		r0 = returnFunc(ctx, userID, query)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *string) error); ok {
		r1 = returnFunc(ctx, userID, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_CountByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByUserID'
type MockFileRepository_CountByUserID_Call struct {
	*mock.Call
}

// CountByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - query *string
func (_e *MockFileRepository_Expecter) CountByUserID(ctx interface{}, userID interface{}, query interface{}) *MockFileRepository_CountByUserID_Call {
	return &MockFileRepository_CountByUserID_Call{Call: _e.mock.On("CountByUserID", ctx, userID, query)}
}

func (_c *MockFileRepository_CountByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID, query *string)) *MockFileRepository_CountByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileRepository_CountByUserID_Call) Return(n int, err error) *MockFileRepository_CountByUserID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockFileRepository_CountByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, query *string) (int, error)) *MockFileRepository_CountByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFile provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) DeleteFile(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileRepository_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockFileRepository_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockFileRepository_Expecter) DeleteFile(ctx interface{}, id interface{}) *MockFileRepository_DeleteFile_Call {
	return &MockFileRepository_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, id)}
}

func (_c *MockFileRepository_DeleteFile_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockFileRepository_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_DeleteFile_Call) Return(err error) *MockFileRepository_DeleteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileRepository_DeleteFile_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockFileRepository_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileByID provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) GetFileByID(ctx context.Context, id uuid.UUID) (model.File, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFileByID")
	}

	var r0 model.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.File, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.File); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.File)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_GetFileByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileByID'
type MockFileRepository_GetFileByID_Call struct {
	*mock.Call
}

// GetFileByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockFileRepository_Expecter) GetFileByID(ctx interface{}, id interface{}) *MockFileRepository_GetFileByID_Call {
	return &MockFileRepository_GetFileByID_Call{Call: _e.mock.On("GetFileByID", ctx, id)}
}

func (_c *MockFileRepository_GetFileByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockFileRepository_GetFileByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_GetFileByID_Call) Return(file model.File, err error) *MockFileRepository_GetFileByID_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileRepository_GetFileByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (model.File, error)) *MockFileRepository_GetFileByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUploadedChunksCount provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) GetUploadedChunksCount(ctx context.Context, fileID uuid.UUID) (int, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for GetUploadedChunksCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_GetUploadedChunksCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUploadedChunksCount'
type MockFileRepository_GetUploadedChunksCount_Call struct {
	*mock.Call
}

// GetUploadedChunksCount is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID uuid.UUID
func (_e *MockFileRepository_Expecter) GetUploadedChunksCount(ctx interface{}, fileID interface{}) *MockFileRepository_GetUploadedChunksCount_Call {
	return &MockFileRepository_GetUploadedChunksCount_Call{Call: _e.mock.On("GetUploadedChunksCount", ctx, fileID)}
}

func (_c *MockFileRepository_GetUploadedChunksCount_Call) Run(run func(ctx context.Context, fileID uuid.UUID)) *MockFileRepository_GetUploadedChunksCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_GetUploadedChunksCount_Call) Return(n int, err error) *MockFileRepository_GetUploadedChunksCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockFileRepository_GetUploadedChunksCount_Call) RunAndReturn(run func(ctx context.Context, fileID uuid.UUID) (int, error)) *MockFileRepository_GetUploadedChunksCount_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) ListByUserID(ctx context.Context, userID uuid.UUID, query *string, limit *int, offset *int) ([]model.File, error) {
	ret := _mock.Called(ctx, userID, query, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []model.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *int, *int) ([]model.File, error)); ok {
		return returnFunc(ctx, userID, query, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *int, *int) []model.File); ok {
		r0 = returnFunc(ctx, userID, query, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *string, *int, *int) error); ok {
		r1 = returnFunc(ctx, userID, query, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockFileRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - query *string
//   - limit *int
//   - offset *int
func (_e *MockFileRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}, query interface{}, limit interface{}, offset interface{}) *MockFileRepository_ListByUserID_Call {
	return &MockFileRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID, query, limit, offset)}
}

func (_c *MockFileRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID, query *string, limit *int, offset *int)) *MockFileRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		var arg4 *int
		if args[4] != nil {
			arg4 = args[4].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockFileRepository_ListByUserID_Call) Return(files []model.File, err error) *MockFileRepository_ListByUserID_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileRepository_ListByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, query *string, limit *int, offset *int) ([]model.File, error)) *MockFileRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NextID provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) NextID(ctx context.Context) uuid.UUID {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NextID")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func(context.Context) uuid.UUID); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// MockFileRepository_NextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextID'
type MockFileRepository_NextID_Call struct {
	*mock.Call
}

// NextID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFileRepository_Expecter) NextID(ctx interface{}) *MockFileRepository_NextID_Call {
	return &MockFileRepository_NextID_Call{Call: _e.mock.On("NextID", ctx)}
}

func (_c *MockFileRepository_NextID_Call) Run(run func(ctx context.Context)) *MockFileRepository_NextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileRepository_NextID_Call) Return(uUID uuid.UUID) *MockFileRepository_NextID_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *MockFileRepository_NextID_Call) RunAndReturn(run func(ctx context.Context) uuid.UUID) *MockFileRepository_NextID_Call {
	_c.Call.Return(run)
	return _c
}

// StoreFile provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) StoreFile(ctx context.Context, file model.File) error {
	ret := _mock.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for StoreFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.File) error); ok {
		r0 = returnFunc(ctx, file)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileRepository_StoreFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreFile'
type MockFileRepository_StoreFile_Call struct {
	*mock.Call
}

// StoreFile is a helper method to define mock.On call
//   - ctx context.Context
//   - file model.File
func (_e *MockFileRepository_Expecter) StoreFile(ctx interface{}, file interface{}) *MockFileRepository_StoreFile_Call {
	return &MockFileRepository_StoreFile_Call{Call: _e.mock.On("StoreFile", ctx, file)}
}

func (_c *MockFileRepository_StoreFile_Call) Run(run func(ctx context.Context, file model.File)) *MockFileRepository_StoreFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.File
		if args[1] != nil {
			arg1 = args[1].(model.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_StoreFile_Call) Return(err error) *MockFileRepository_StoreFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileRepository_StoreFile_Call) RunAndReturn(run func(ctx context.Context, file model.File) error) *MockFileRepository_StoreFile_Call {
	_c.Call.Return(run)
	return _c
}

// StoreFileChunks provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) StoreFileChunks(ctx context.Context, chunks []model.FileChunk) error {
	ret := _mock.Called(ctx, chunks)

	if len(ret) == 0 {
		panic("no return value specified for StoreFileChunks")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []model.FileChunk) error); ok {
		r0 = returnFunc(ctx, chunks)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileRepository_StoreFileChunks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreFileChunks'
type MockFileRepository_StoreFileChunks_Call struct {
	*mock.Call
}

// StoreFileChunks is a helper method to define mock.On call
//   - ctx context.Context
//   - chunks []model.FileChunk
func (_e *MockFileRepository_Expecter) StoreFileChunks(ctx interface{}, chunks interface{}) *MockFileRepository_StoreFileChunks_Call {
	return &MockFileRepository_StoreFileChunks_Call{Call: _e.mock.On("StoreFileChunks", ctx, chunks)}
}

func (_c *MockFileRepository_StoreFileChunks_Call) Run(run func(ctx context.Context, chunks []model.FileChunk)) *MockFileRepository_StoreFileChunks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []model.FileChunk
		if args[1] != nil {
			arg1 = args[1].([]model.FileChunk)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_StoreFileChunks_Call) Return(err error) *MockFileRepository_StoreFileChunks_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileRepository_StoreFileChunks_Call) RunAndReturn(run func(ctx context.Context, chunks []model.FileChunk) error) *MockFileRepository_StoreFileChunks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateChunkUploaded provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) UpdateChunkUploaded(ctx context.Context, fileID uuid.UUID, chunkIndex int, uploaded bool) error {
	ret := _mock.Called(ctx, fileID, chunkIndex, uploaded)

	if len(ret) == 0 {
		panic("no return value specified for UpdateChunkUploaded")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, bool) error); ok {
		r0 = returnFunc(ctx, fileID, chunkIndex, uploaded)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileRepository_UpdateChunkUploaded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateChunkUploaded'
type MockFileRepository_UpdateChunkUploaded_Call struct {
	*mock.Call
}

// UpdateChunkUploaded is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID uuid.UUID
//   - chunkIndex int
//   - uploaded bool
func (_e *MockFileRepository_Expecter) UpdateChunkUploaded(ctx interface{}, fileID interface{}, chunkIndex interface{}, uploaded interface{}) *MockFileRepository_UpdateChunkUploaded_Call {
	return &MockFileRepository_UpdateChunkUploaded_Call{Call: _e.mock.On("UpdateChunkUploaded", ctx, fileID, chunkIndex, uploaded)}
}

func (_c *MockFileRepository_UpdateChunkUploaded_Call) Run(run func(ctx context.Context, fileID uuid.UUID, chunkIndex int, uploaded bool)) *MockFileRepository_UpdateChunkUploaded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFileRepository_UpdateChunkUploaded_Call) Return(err error) *MockFileRepository_UpdateChunkUploaded_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileRepository_UpdateChunkUploaded_Call) RunAndReturn(run func(ctx context.Context, fileID uuid.UUID, chunkIndex int, uploaded bool) error) *MockFileRepository_UpdateChunkUploaded_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFileStatus provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) UpdateFileStatus(ctx context.Context, id uuid.UUID, status model.FileStatus) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFileStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.FileStatus) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileRepository_UpdateFileStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFileStatus'
type MockFileRepository_UpdateFileStatus_Call struct {
	*mock.Call
}

// UpdateFileStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status model.FileStatus
func (_e *MockFileRepository_Expecter) UpdateFileStatus(ctx interface{}, id interface{}, status interface{}) *MockFileRepository_UpdateFileStatus_Call {
	return &MockFileRepository_UpdateFileStatus_Call{Call: _e.mock.On("UpdateFileStatus", ctx, id, status)}
}

func (_c *MockFileRepository_UpdateFileStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status model.FileStatus)) *MockFileRepository_UpdateFileStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 model.FileStatus
		if args[2] != nil {
			arg2 = args[2].(model.FileStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileRepository_UpdateFileStatus_Call) Return(err error) *MockFileRepository_UpdateFileStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileRepository_UpdateFileStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, status model.FileStatus) error) *MockFileRepository_UpdateFileStatus_Call {
	_c.Call.Return(run)
	return _c
}
