// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BankCardDataType.
const (
	BankCardDataTypeBANKCARD BankCardDataType = "BANK_CARD"
)

// Valid indicates whether the value is a known member of the BankCardDataType enum.
func (e BankCardDataType) Valid() bool {
	switch e {
	case BankCardDataTypeBANKCARD:
		return true
	default:
		return false
	}
}

// Defines values for BankCardDataInfoType.
const (
	BankCardDataInfoTypeBANKCARD BankCardDataInfoType = "BANK_CARD"
)

// Valid indicates whether the value is a known member of the BankCardDataInfoType enum.
func (e BankCardDataInfoType) Valid() bool {
	switch e {
	case BankCardDataInfoTypeBANKCARD:
		return true
	default:
		return false
	}
}

// Defines values for DataType.
const (
	DataTypeBANKCARD      DataType = "BANK_CARD"
	DataTypeFILE          DataType = "FILE"
	DataTypeLOGINPASSWORD DataType = "LOGIN_PASSWORD"
	DataTypeTEXT          DataType = "TEXT"
)

// Valid indicates whether the value is a known member of the DataType enum.
func (e DataType) Valid() bool {
	switch e {
	case DataTypeBANKCARD:
		return true
	case DataTypeFILE:
		return true
	case DataTypeLOGINPASSWORD:
		return true
	case DataTypeTEXT:
		return true
	default:
		return false
	}
}

// Defines values for FileDataType.
const (
	FileDataTypeFILE FileDataType = "FILE"
)

// Valid indicates whether the value is a known member of the FileDataType enum.
func (e FileDataType) Valid() bool {
	switch e {
	case FileDataTypeFILE:
		return true
	default:
		return false
	}
}

// Defines values for FileDataInfoType.
const (
	FileDataInfoTypeFILE FileDataInfoType = "FILE"
)

// Valid indicates whether the value is a known member of the FileDataInfoType enum.
func (e FileDataInfoType) Valid() bool {
	switch e {
	case FileDataInfoTypeFILE:
		return true
	default:
		return false
	}
}

// Defines values for FileStatus.
const (
	COMPLETED  FileStatus = "COMPLETED"
	FAILED     FileStatus = "FAILED"
	INPROGRESS FileStatus = "IN_PROGRESS"
)

// Valid indicates whether the value is a known member of the FileStatus enum.
func (e FileStatus) Valid() bool {
	switch e {
	case COMPLETED:
		return true
	case FAILED:
		return true
	case INPROGRESS:
		return true
	default:
		return false
	}
}

// Defines values for LoginPasswordDataType.
const (
	LoginPasswordDataTypeLOGINPASSWORD LoginPasswordDataType = "LOGIN_PASSWORD"
)

// Valid indicates whether the value is a known member of the LoginPasswordDataType enum.
func (e LoginPasswordDataType) Valid() bool {
	switch e {
	case LoginPasswordDataTypeLOGINPASSWORD:
		return true
	default:
		return false
	}
}

// Defines values for LoginPasswordDataInfoType.
const (
	LoginPasswordDataInfoTypeLOGINPASSWORD LoginPasswordDataInfoType = "LOGIN_PASSWORD"
)

// Valid indicates whether the value is a known member of the LoginPasswordDataInfoType enum.
func (e LoginPasswordDataInfoType) Valid() bool {
	switch e {
	case LoginPasswordDataInfoTypeLOGINPASSWORD:
		return true
	default:
		return false
	}
}

// Defines values for TextDataType.
const (
	TextDataTypeTEXT TextDataType = "TEXT"
)

// Valid indicates whether the value is a known member of the TextDataType enum.
func (e TextDataType) Valid() bool {
	switch e {
	case TextDataTypeTEXT:
		return true
	default:
		return false
	}
}

// Defines values for TextDataInfoType.
const (
	TextDataInfoTypeTEXT TextDataInfoType = "TEXT"
)

// Valid indicates whether the value is a known member of the TextDataInfoType enum.
func (e TextDataInfoType) Valid() bool {
	switch e {
	case TextDataInfoTypeTEXT:
		return true
	default:
		return false
	}
}

// BankCardData defines model for bankCardData.
type BankCardData struct {
	CardCvv string `json:"card_cvv"`

	// CardExpiry Card expiry date (MM/YY)
	CardExpiry string `json:"card_expiry"`
	CardHolder string `json:"card_holder"`
	CardNumber string `json:"card_number"`

	// Metadata Arbitrary text metadata (unencrypted)
	Metadata *string          `json:"metadata,omitempty"`
	Type     BankCardDataType `json:"type"`
}

// BankCardDataType defines model for BankCardData.Type.
type BankCardDataType string

// BankCardDataInfo defines model for bankCardDataInfo.
type BankCardDataInfo struct {
	CardCvv string `json:"card_cvv"`

	// CardExpiry Card expiry date (MM/YY)
	CardExpiry string             `json:"card_expiry"`
	CardHolder string             `json:"card_holder"`
	CardNumber string             `json:"card_number"`
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`

	// Metadata Arbitrary text metadata (unencrypted)
	Metadata  *string              `json:"metadata,omitempty"`
	Type      BankCardDataInfoType `json:"type"`
	UpdatedAt time.Time            `json:"updated_at"`
}

// BankCardDataInfoType defines model for BankCardDataInfo.Type.
type BankCardDataInfoType string

// BaseData defines model for baseData.
type BaseData struct {
	// Metadata Arbitrary text metadata (unencrypted)
	Metadata *string `json:"metadata,omitempty"`
}

// BaseDataInfo defines model for baseDataInfo.
type BaseDataInfo struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`

	// Type Type of data entry
	Type      DataType  `json:"type"`
	UpdatedAt time.Time `json:"updated_at"`
}

// CreateDataRequest defines model for createDataRequest.
type CreateDataRequest struct {
	Data *Data `json:"data,omitempty"`
}

// CreateDataResponse defines model for createDataResponse.
type CreateDataResponse struct {
	Data *DataInfo `json:"data,omitempty"`
}

// Data defines model for data.
type Data struct {
	union json.RawMessage
}

// DataInfo defines model for dataInfo.
type DataInfo struct {
	union json.RawMessage
}

// DataType Type of data entry
type DataType string

// Error defines model for error.
type Error struct {
	// Message Error message
	Message string `json:"message"`
}

// FileChunkResponse defines model for fileChunkResponse.
type FileChunkResponse struct {
	ChunkIndex int                `json:"chunk_index"`
	FileId     openapi_types.UUID `json:"file_id"`
	Uploaded   bool               `json:"uploaded"`
}

// FileCompleteRequest defines model for fileCompleteRequest.
type FileCompleteRequest struct {
	FileId openapi_types.UUID `json:"file_id"`
}

// FileData defines model for fileData.
type FileData struct {
	FileIds []openapi_types.UUID `json:"file_ids"`

	// Metadata Arbitrary text metadata (unencrypted)
	Metadata *string      `json:"metadata,omitempty"`
	Type     FileDataType `json:"type"`
}

// FileDataType defines model for FileData.Type.
type FileDataType string

// FileDataInfo defines model for fileDataInfo.
type FileDataInfo struct {
	CreatedAt time.Time            `json:"created_at"`
	FileIds   []openapi_types.UUID `json:"file_ids"`
	Id        openapi_types.UUID   `json:"id"`

	// Metadata Arbitrary text metadata (unencrypted)
	Metadata  *string          `json:"metadata,omitempty"`
	Type      FileDataInfoType `json:"type"`
	UpdatedAt time.Time        `json:"updated_at"`
}

// FileDataInfoType defines model for FileDataInfo.Type.
type FileDataInfoType string

// FileInfo defines model for fileInfo.
type FileInfo struct {
	ChunksCount int                `json:"chunks_count"`
	CreatedAt   time.Time          `json:"created_at"`
	Id          openapi_types.UUID `json:"id"`
	MimeType    string             `json:"mime_type"`
	Name        string             `json:"name"`
	Size        int64              `json:"size"`

	// Status Status of the file upload
	Status    FileStatus `json:"status"`
	UpdatedAt time.Time  `json:"updated_at"`
}

// FileInitRequest defines model for fileInitRequest.
type FileInitRequest struct {
	ChunksCount int    `json:"chunks_count"`
	MimeType    string `json:"mime_type"`
	Name        string `json:"name"`
	Size        int64  `json:"size"`
}

// FileInitResponse defines model for fileInitResponse.
type FileInitResponse struct {
	ChunksCount int                `json:"chunks_count"`
	FileId      openapi_types.UUID `json:"file_id"`
}

// FileStatus Status of the file upload
type FileStatus string

// HealthResponse defines model for healthResponse.
type HealthResponse struct {
	// Status Example: ok
	Status string `json:"status"`

	// Version Example: 1.0.0
	Version *string `json:"version,omitempty"`
}

// ListDataResponse defines model for listDataResponse.
type ListDataResponse struct {
	Items      []DataInfo `json:"items"`
	Page       int        `json:"page"`
	PageSize   int        `json:"page_size"`
	Total      int        `json:"total"`
	TotalPages int        `json:"total_pages"`
}

// ListFilesResponse defines model for listFilesResponse.
type ListFilesResponse struct {
	Items      []FileInfo `json:"items"`
	Page       int        `json:"page"`
	PageSize   int        `json:"page_size"`
	Total      int        `json:"total"`
	TotalPages int        `json:"total_pages"`
}

// LoginPasswordData defines model for loginPasswordData.
type LoginPasswordData struct {
	Login string `json:"login"`

	// Metadata Arbitrary text metadata (unencrypted)
	Metadata *string               `json:"metadata,omitempty"`
	Password string                `json:"password"`
	Type     LoginPasswordDataType `json:"type"`
}

// LoginPasswordDataType defines model for LoginPasswordData.Type.
type LoginPasswordDataType string

// LoginPasswordDataInfo defines model for loginPasswordDataInfo.
type LoginPasswordDataInfo struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Login     string             `json:"login"`

	// Metadata Arbitrary text metadata (unencrypted)
	Metadata  *string                   `json:"metadata,omitempty"`
	Password  string                    `json:"password"`
	Type      LoginPasswordDataInfoType `json:"type"`
	UpdatedAt time.Time                 `json:"updated_at"`
}

// LoginPasswordDataInfoType defines model for LoginPasswordDataInfo.Type.
type LoginPasswordDataInfoType string

// LoginRequest defines model for loginRequest.
type LoginRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// RefreshRequest defines model for refreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for registerRequest.
type RegisterRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// TextData defines model for textData.
type TextData struct {
	// Metadata Arbitrary text metadata (unencrypted)
	Metadata *string      `json:"metadata,omitempty"`
	Text     string       `json:"text"`
	Type     TextDataType `json:"type"`
}

// TextDataType defines model for TextData.Type.
type TextDataType string

// TextDataInfo defines model for textDataInfo.
type TextDataInfo struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`

	// Metadata Arbitrary text metadata (unencrypted)
	Metadata  *string          `json:"metadata,omitempty"`
	Text      string           `json:"text"`
	Type      TextDataInfoType `json:"type"`
	UpdatedAt time.Time        `json:"updated_at"`
}

// TextDataInfoType defines model for TextDataInfo.Type.
type TextDataInfoType string

// TokenResponse defines model for tokenResponse.
type TokenResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Access token expiration time in seconds
	ExpiresIn    int    `json:"expires_in"`
	RefreshToken string `json:"refresh_token"`

	// RefreshTokenExpiresIn Refresh token expiration time in seconds
	RefreshTokenExpiresIn int `json:"refresh_token_expires_in"`

	// TokenType Example: bearer
	TokenType string `json:"token_type"`
}

// UpdateDataRequest defines model for updateDataRequest.
type UpdateDataRequest struct {
	Data *Data `json:"data,omitempty"`
}

// UpdateDataResponse defines model for updateDataResponse.
type UpdateDataResponse struct {
	Data *DataInfo `json:"data,omitempty"`
}

// User defines model for user.
type User struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Login     string             `json:"login"`
}

// BadRequest defines model for badRequest.
type BadRequest = Error

// Conflict defines model for conflict.
type Conflict = Error

// NotFound defines model for notFound.
type NotFound = Error

// ServerError defines model for serverError.
type ServerError = Error

// Unauthorized defines model for unauthorized.
type Unauthorized = Error

// ListDataParams defines parameters for ListData.
type ListDataParams struct {
	// Page Page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Types Filter by entry types (comma-separated)
	Types *[]DataType `form:"types,omitempty" json:"types,omitempty"`

	// Query Search query (searches by metadata)
	Query *string `form:"query,omitempty" json:"query,omitempty"`
}

// ListFilesParams defines parameters for ListFiles.
type ListFilesParams struct {
	// Page Page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Query Search query (searches by file name)
	Query *string `form:"query,omitempty" json:"query,omitempty"`
}

// UploadChunkMultipartBody defines parameters for UploadChunk.
type UploadChunkMultipartBody struct {
	ChunkIndex int                `json:"chunk_index"`
	Data       openapi_types.File `json:"data"`
	FileId     openapi_types.UUID `json:"file_id"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// CreateDataJSONRequestBody defines body for CreateData for application/json ContentType.
type CreateDataJSONRequestBody = CreateDataRequest

// UpdateDataJSONRequestBody defines body for UpdateData for application/json ContentType.
type UpdateDataJSONRequestBody = UpdateDataRequest

// UploadChunkMultipartRequestBody defines body for UploadChunk for multipart/form-data ContentType.
type UploadChunkMultipartRequestBody UploadChunkMultipartBody

// CompleteUploadJSONRequestBody defines body for CompleteUpload for application/json ContentType.
type CompleteUploadJSONRequestBody = FileCompleteRequest

// InitUploadJSONRequestBody defines body for InitUpload for application/json ContentType.
type InitUploadJSONRequestBody = FileInitRequest

// AsLoginPasswordData returns the union data inside the Data as a LoginPasswordData
func (t Data) AsLoginPasswordData() (LoginPasswordData, error) {
	var body LoginPasswordData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLoginPasswordData overwrites any union data inside the Data as the provided LoginPasswordData
func (t *Data) FromLoginPasswordData(v LoginPasswordData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"LOGIN_PASSWORD"}`))
	t.union = b
	return err
}

// MergeLoginPasswordData performs a merge with any union data inside the Data, using the provided LoginPasswordData
func (t *Data) MergeLoginPasswordData(v LoginPasswordData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"LOGIN_PASSWORD"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBankCardData returns the union data inside the Data as a BankCardData
func (t Data) AsBankCardData() (BankCardData, error) {
	var body BankCardData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBankCardData overwrites any union data inside the Data as the provided BankCardData
func (t *Data) FromBankCardData(v BankCardData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"BANK_CARD"}`))
	t.union = b
	return err
}

// MergeBankCardData performs a merge with any union data inside the Data, using the provided BankCardData
func (t *Data) MergeBankCardData(v BankCardData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"BANK_CARD"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTextData returns the union data inside the Data as a TextData
func (t Data) AsTextData() (TextData, error) {
	var body TextData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextData overwrites any union data inside the Data as the provided TextData
func (t *Data) FromTextData(v TextData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"TEXT"}`))
	t.union = b
	return err
}

// MergeTextData performs a merge with any union data inside the Data, using the provided TextData
func (t *Data) MergeTextData(v TextData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"TEXT"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFileData returns the union data inside the Data as a FileData
func (t Data) AsFileData() (FileData, error) {
	var body FileData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFileData overwrites any union data inside the Data as the provided FileData
func (t *Data) FromFileData(v FileData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"FILE"}`))
	t.union = b
	return err
}

// MergeFileData performs a merge with any union data inside the Data, using the provided FileData
func (t *Data) MergeFileData(v FileData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"FILE"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Data) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Data) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "BANK_CARD":
		return t.AsBankCardData()
	case "FILE":
		return t.AsFileData()
	case "LOGIN_PASSWORD":
		return t.AsLoginPasswordData()
	case "TEXT":
		return t.AsTextData()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsLoginPasswordDataInfo returns the union data inside the DataInfo as a LoginPasswordDataInfo
func (t DataInfo) AsLoginPasswordDataInfo() (LoginPasswordDataInfo, error) {
	var body LoginPasswordDataInfo
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLoginPasswordDataInfo overwrites any union data inside the DataInfo as the provided LoginPasswordDataInfo
func (t *DataInfo) FromLoginPasswordDataInfo(v LoginPasswordDataInfo) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"LOGIN_PASSWORD"}`))
	t.union = b
	return err
}

// MergeLoginPasswordDataInfo performs a merge with any union data inside the DataInfo, using the provided LoginPasswordDataInfo
func (t *DataInfo) MergeLoginPasswordDataInfo(v LoginPasswordDataInfo) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"LOGIN_PASSWORD"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBankCardDataInfo returns the union data inside the DataInfo as a BankCardDataInfo
func (t DataInfo) AsBankCardDataInfo() (BankCardDataInfo, error) {
	var body BankCardDataInfo
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBankCardDataInfo overwrites any union data inside the DataInfo as the provided BankCardDataInfo
func (t *DataInfo) FromBankCardDataInfo(v BankCardDataInfo) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"BANK_CARD"}`))
	t.union = b
	return err
}

// MergeBankCardDataInfo performs a merge with any union data inside the DataInfo, using the provided BankCardDataInfo
func (t *DataInfo) MergeBankCardDataInfo(v BankCardDataInfo) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"BANK_CARD"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTextDataInfo returns the union data inside the DataInfo as a TextDataInfo
func (t DataInfo) AsTextDataInfo() (TextDataInfo, error) {
	var body TextDataInfo
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextDataInfo overwrites any union data inside the DataInfo as the provided TextDataInfo
func (t *DataInfo) FromTextDataInfo(v TextDataInfo) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"TEXT"}`))
	t.union = b
	return err
}

// MergeTextDataInfo performs a merge with any union data inside the DataInfo, using the provided TextDataInfo
func (t *DataInfo) MergeTextDataInfo(v TextDataInfo) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"TEXT"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFileDataInfo returns the union data inside the DataInfo as a FileDataInfo
func (t DataInfo) AsFileDataInfo() (FileDataInfo, error) {
	var body FileDataInfo
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFileDataInfo overwrites any union data inside the DataInfo as the provided FileDataInfo
func (t *DataInfo) FromFileDataInfo(v FileDataInfo) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"FILE"}`))
	t.union = b
	return err
}

// MergeFileDataInfo performs a merge with any union data inside the DataInfo, using the provided FileDataInfo
func (t *DataInfo) MergeFileDataInfo(v FileDataInfo) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"FILE"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t DataInfo) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t DataInfo) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "BANK_CARD":
		return t.AsBankCardDataInfo()
	case "FILE":
		return t.AsFileDataInfo()
	case "LOGIN_PASSWORD":
		return t.AsLoginPasswordDataInfo()
	case "TEXT":
		return t.AsTextDataInfo()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t DataInfo) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *DataInfo) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// LoginUser Login and get tokens
	// (POST /api/v1/auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// RefreshToken Refresh access token
	// (POST /api/v1/auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// RegisterUser Register a new user
	// (POST /api/v1/auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// CreateData Create a new data entry
	// (POST /api/v1/data)
	CreateData(w http.ResponseWriter, r *http.Request)
	// ListData List data entries with filtering and pagination
	// (GET /api/v1/data/list)
	ListData(w http.ResponseWriter, r *http.Request, params ListDataParams)
	// DeleteData Delete a data entry
	// (DELETE /api/v1/data/{id})
	DeleteData(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetData Get a data entry by ID
	// (GET /api/v1/data/{id})
	GetData(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateData Update a data entry
	// (PUT /api/v1/data/{id})
	UpdateData(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ListFiles List user's files with pagination and search
	// (GET /api/v1/file/list)
	ListFiles(w http.ResponseWriter, r *http.Request, params ListFilesParams)
	// UploadChunk Upload a file chunk
	// (POST /api/v1/file/upload/chunk)
	UploadChunk(w http.ResponseWriter, r *http.Request)
	// CompleteUpload Complete file upload
	// (POST /api/v1/file/upload/complete)
	CompleteUpload(w http.ResponseWriter, r *http.Request)
	// InitUpload Initialize a new file upload
	// (POST /api/v1/file/upload/init)
	InitUpload(w http.ResponseWriter, r *http.Request)
	// DeleteFile Delete a file
	// (DELETE /api/v1/file/{id})
	DeleteFile(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// DownloadFile Download a file
	// (GET /api/v1/file/{id}/download)
	DownloadFile(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// HealthCheck Health check
	// (GET /api/v1/health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// LoginUser Login and get tokens
// (POST /api/v1/auth/login)
func (_ Unimplemented) LoginUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RefreshToken Refresh access token
// (POST /api/v1/auth/refresh)
func (_ Unimplemented) RefreshToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RegisterUser Register a new user
// (POST /api/v1/auth/register)
func (_ Unimplemented) RegisterUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateData Create a new data entry
// (POST /api/v1/data)
func (_ Unimplemented) CreateData(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListData List data entries with filtering and pagination
// (GET /api/v1/data/list)
func (_ Unimplemented) ListData(w http.ResponseWriter, r *http.Request, params ListDataParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteData Delete a data entry
// (DELETE /api/v1/data/{id})
func (_ Unimplemented) DeleteData(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetData Get a data entry by ID
// (GET /api/v1/data/{id})
func (_ Unimplemented) GetData(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateData Update a data entry
// (PUT /api/v1/data/{id})
func (_ Unimplemented) UpdateData(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListFiles List user's files with pagination and search
// (GET /api/v1/file/list)
func (_ Unimplemented) ListFiles(w http.ResponseWriter, r *http.Request, params ListFilesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UploadChunk Upload a file chunk
// (POST /api/v1/file/upload/chunk)
func (_ Unimplemented) UploadChunk(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CompleteUpload Complete file upload
// (POST /api/v1/file/upload/complete)
func (_ Unimplemented) CompleteUpload(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// InitUpload Initialize a new file upload
// (POST /api/v1/file/upload/init)
func (_ Unimplemented) InitUpload(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteFile Delete a file
// (DELETE /api/v1/file/{id})
func (_ Unimplemented) DeleteFile(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DownloadFile Download a file
// (GET /api/v1/file/{id}/download)
func (_ Unimplemented) DownloadFile(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// HealthCheck Health check
// (GET /api/v1/health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateData operation middleware
func (siw *ServerInterfaceWrapper) CreateData(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateData(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListData operation middleware
func (siw *ServerInterfaceWrapper) ListData(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDataParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "types" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "types", r.URL.Query(), &params.Types, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "types"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "types", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "query", r.URL.Query(), &params.Query, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListData(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteData operation middleware
func (siw *ServerInterfaceWrapper) DeleteData(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteData(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetData operation middleware
func (siw *ServerInterfaceWrapper) GetData(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetData(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateData operation middleware
func (siw *ServerInterfaceWrapper) UpdateData(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateData(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFiles operation middleware
func (siw *ServerInterfaceWrapper) ListFiles(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFilesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "query", r.URL.Query(), &params.Query, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFiles(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadChunk operation middleware
func (siw *ServerInterfaceWrapper) UploadChunk(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadChunk(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteUpload operation middleware
func (siw *ServerInterfaceWrapper) CompleteUpload(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteUpload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InitUpload operation middleware
func (siw *ServerInterfaceWrapper) InitUpload(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InitUpload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteFile operation middleware
func (siw *ServerInterfaceWrapper) DeleteFile(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFile(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadFile operation middleware
func (siw *ServerInterfaceWrapper) DownloadFile(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadFile(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/health", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/register", wrapper.RegisterUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/login", wrapper.LoginUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/refresh", wrapper.RefreshToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/data", wrapper.CreateData)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/data/list", wrapper.ListData)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/data/{id}", wrapper.DeleteData)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/data/{id}", wrapper.GetData)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/data/{id}", wrapper.UpdateData)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/file/upload/init", wrapper.InitUpload)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/file/upload/chunk", wrapper.UploadChunk)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/file/upload/complete", wrapper.CompleteUpload)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/file/{id}/download", wrapper.DownloadFile)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/file/{id}", wrapper.DeleteFile)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/file/list", wrapper.ListFiles)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Ft7b9s4Ev8qBO+A6wFq7bRp0fN/aR693KYP5IG9RREYjDS2uZVILUml8Qb+7gc+JFMSJSs5Ow0O959t",
	"DjnD+c2LQ/oexzzLOQOmJJ7cYwEy50yC+XJDknP4owCp9LeYMwXMfCR5ntKYKMrZ6HfJmf5NxgvIiP70",
	"VwEzPMF/Ga2XHtlROQIhuMCr1SrCCchY0Fwvgif4A0mQcMxWkWY2S2n8BIwPS06rCDOuTnjBkt1z/cwV",
	"mhlWqwhLELcgjg3tzjlfGGaISlSwBZBULZZahoKRQi24oH/CE2z/yuemh90Ma3Xs+yERyRFRhgFJ0y8z",
	"PPnWz+qGSDAzVtE9zgXPQShqzTgmIpnGt7f6s1rmgCdYKkHZ3BiaHoS7nIqlHm/YBhEJsoMoIQrQi0+f",
	"Rr/99nccdSy04GkCopsRK7KbjnH7wz0GVmR48g1/OPj8y/Tw4PwIX7e4rSKsfYUKjdU3O1rnUJenvs1o",
	"rZH10vzmd9BOcL2Kagicshl/OApmlkain9gDetUWRQviQJ00Mc1AkcSN1DE7EDdUCSKWSMGdQiUhelEw",
	"YLFY5goSDWBG7s6AzdUCT969ffvmXUjJnQKVWmkYmgCiIJkS4zYzLjL9CWvLealoBiGzoUmNtihoEiIr",
	"raNPn3qbl5pOu3OePFCUhk2txYj8fdVWDkFmabWOvNRRV1OJ26a9hCHwGdhc9XgO1kxDXCrbotq2MsqI",
	"ssE5I3mu9TW59zx0iIFH+OT07LiLdEZTcGRnXz6efp5+Pbi4+PVL99opn1P2lUj5g1cMLo//fdlFr53B",
	"xcdSWcvPJNO7Vs5mOIMBLt5m/DA/30DsydlPWGksGDkSz0m3hqFZcBiOjvSRWLrZQ/B0kXbLmD44fg+a",
	"0JB5GL6WuAvjSxcX6zlA/4r4DJnAD0yZpFcm1gYmkWcDTuUO4utAHIaySGumIynJPCCJKepQObwp6JZ0",
	"od1qfRwuCva9O+zFenhKWQJ3XolBmYI5iHKN6cCMU+QpJ4ktBt3gDecpENYSu1w2qkngLdG5H57lKSjo",
	"TBXDBe4QqYvz1opLx8h8pgoy+YB0jokQZBkq/jrsL1z3VSKEq7maI+2mkuuPxXq0o2DS5iKnMS/sSaNt",
	"sTssqTKawbRUfGuUmTgaGJD0T6itT5l6t79m4AkvFVGF3FSIaPVcWMqtFW5Gen+LTu6orvJKxIfVeBZQ",
	"qjrdtolrRhnNtGXvhdRUA8Iry1+/fRd1A+MR7o1f70cPQKoSZ9wWp6HNgYrs11JvvO41//86/g2U86Ky",
	"1EazwPyuU6laANKUyAZ1L5/qZHr+5eP58cUFjvDhl09fz44vj3UyPTk4PTs+CuZR23noVs3adeCO6CSh",
	"Rf4ecuNbEJLapsSadO/V+NV4o5Ick5BSUipV/xmjCvbVh2GnjXbwz13l0IZfj0xLM24PK65I2jM01fNl",
	"iKAZM8wWygWdRD77+oJdCjuhKchtaazKGv+zGmsdpLZRj5hVg4krd6wGdZ8aRfLQUsRy93iFS5LweWM3",
	"tUngvNqJRmdCe5RWGyoaoBs9YSZALjoFceNTxb8D28yzTh5mOKdSgdi8db9htm+SaPn1TdSvFz9Vv35f",
	"m7ofbUNrVdNgGx6kFxvkI+asONQzzKphb6gdi3fjBOuuSlB92jq64zaJY5Cy0+QibPrKIKfWThrtWDMZ",
	"mcm2lW4uEpCuZRFlSELMWSKD9fMmY29QTPvkOLeUjxPELl/hX5UZN0CEaa9vMIH19KiuzeYea7rs2V4I",
	"RVu077Dz6jPYXee1kCCetLXeFdtD56oyGnnitKEwN3pxIahaXugt2x18MLZyUOiod+8s56SU7V+/XmJ3",
	"CRayq4VSub1Go2VPs2bcZXpDGWFkDgKdH19cooOvp3oJqoytfuT54heAHIQbqApnVy2vIsxzYCSneILf",
	"vBq/emPCrloY8Uckp6PbvREp1GJUqSzn1sw0VMadThM8wWd6+EqaHbg73Q88WW7tWrGWq1d1oJQowPzg",
	"3WO/Ho+3xrseKwNXm2bzSBbGzWdFqvW6bwUIrVsJOvJu282Uvc1TitY1apFlRCwrMQhL0ByUjXomtpG5",
	"1Nas5+FrPaUGrAs43dC6MHpZRa/to9sogZ4bvmbryAkJiYd0uvxJWJe5jXi5dgjWtvLrA9tS7NCVm+Xn",
	"ILT3tsbeJJvQ+wQJApWybQvkf2yeUj17aQJsJUEEMfiBCotHN75lFg7DeljdoO4I1PYd8BPDGrgjDoB8",
	"VN0OIZfPHwWtl+5N0e4n+m/XuuBeA2lV72Cs3U6VYBroWmCOUmqRnEMo37pmlcnXgmSgQEgjS7NMmAOq",
	"HojoDI7/KMCwt13Vso2x1nICM1KkynRu+7q4+gDSeOFk+CA+Q6ZXgnTh4Zbv4lx2TgLsX4/Niw3Hfzx+",
	"qDQnNNX+c7N0gOsZEr2IeZaRlxK02ty7kJBwhromGNzlKU8AT2YklRANbwKWDzSkWpqyTJenuNnhast/",
	"AUTEC2TkQi+k+QZS76d84NIle/l1LXuzzr3eYTpt9VFDFROVqnZbq2v+XXuiYepzRD+oWqCZsRPK5qZ0",
	"ysmcMrPtzR56T5OVNdkUFLSd9Mj8PsRNvbh0elSiqgvxNajmMFKPpz7Cm+4K2ojvtw8Vnhh2Ty487m8G",
	"pXpH+SBIrIYQ6Q2MUTgEfgT1XFW7PWfyDs49yWzHKH0EVYNIxyCjyxZQeREA6qpqIjwTrLZf/rQbMU98",
	"hgk0avrLH3ff++jKdmfGZq1lQ0jwIvGMprC5VjL3VP8vljql6S42zA2wFuL5Vhv1S8iecmNmrOBJ6gx9",
	"YPubtBxtnbGuLEyhYXXsmbYmDZi2vXwfmTv97gPelaEyj8V6T3hZkSqaE6FGOlK+LE+Na133Pi/re0Wx",
	"fkBbxeAbyoj13mYDdluPHKp3ZzYutPuyTxqE2+/1Qn8+0QSoeif3DOOvlgwR6/ixs6iBRuoe9/U0IhzF",
	"VfmkZBfZOPTO8CeYQlfddrJ+U4NKjT1DQyg12HgDNMwSKKOq2wpOGVU7twD/udoTN6Na78A2WIHWFiWp",
	"7fPuODudVrxcT+pB8A478uq9bSq2zP5/5mHXCPDEx9yZVcwAJY8S/oMZTLrK2iNH8PyU3RdGeaxAvZRK",
	"AMnqDrWxbOjwoZLRjiF02h4Con3p2AncP83w4QJiW6vtKAU13lv2/i/U+1fo2yHBx//7av3ewm4OxW53",
	"pZLkUirItJqqP7+G7PSMxyRFCdxCyvMMmEKWFke4EKm7Fp+MRqmmW3CpJu/H78f2iYvldF9ateOojzru",
	"F3Np4n1PysdA7rsBcnW9+k8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
