// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"
	"io"

	"github.com/google/uuid"
	"github.com/liebeSonne/gophkeeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileService creates a new instance of MockFileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileService {
	mock := &MockFileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileService is an autogenerated mock type for the FileService type
type MockFileService struct {
	mock.Mock
}

type MockFileService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileService) EXPECT() *MockFileService_Expecter {
	return &MockFileService_Expecter{mock: &_m.Mock}
}

// CompleteUpload provides a mock function for the type MockFileService
func (_mock *MockFileService) CompleteUpload(ctx context.Context, fileID uuid.UUID, userID uuid.UUID) (model.File, error) {
	ret := _mock.Called(ctx, fileID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CompleteUpload")
	}

	var r0 model.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (model.File, error)); ok {
		return returnFunc(ctx, fileID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) model.File); ok {
		r0 = returnFunc(ctx, fileID, userID)
	} else {
		r0 = ret.Get(0).(model.File)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, fileID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileService_CompleteUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteUpload'
type MockFileService_CompleteUpload_Call struct {
	*mock.Call
}

// CompleteUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID uuid.UUID
//   - userID uuid.UUID
func (_e *MockFileService_Expecter) CompleteUpload(ctx interface{}, fileID interface{}, userID interface{}) *MockFileService_CompleteUpload_Call {
	return &MockFileService_CompleteUpload_Call{Call: _e.mock.On("CompleteUpload", ctx, fileID, userID)}
}

func (_c *MockFileService_CompleteUpload_Call) Run(run func(ctx context.Context, fileID uuid.UUID, userID uuid.UUID)) *MockFileService_CompleteUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileService_CompleteUpload_Call) Return(file model.File, err error) *MockFileService_CompleteUpload_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileService_CompleteUpload_Call) RunAndReturn(run func(ctx context.Context, fileID uuid.UUID, userID uuid.UUID) (model.File, error)) *MockFileService_CompleteUpload_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFile provides a mock function for the type MockFileService
func (_mock *MockFileService) DeleteFile(ctx context.Context, fileID uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, fileID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, fileID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileService_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockFileService_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID uuid.UUID
//   - userID uuid.UUID
func (_e *MockFileService_Expecter) DeleteFile(ctx interface{}, fileID interface{}, userID interface{}) *MockFileService_DeleteFile_Call {
	return &MockFileService_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, fileID, userID)}
}

func (_c *MockFileService_DeleteFile_Call) Run(run func(ctx context.Context, fileID uuid.UUID, userID uuid.UUID)) *MockFileService_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileService_DeleteFile_Call) Return(err error) *MockFileService_DeleteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileService_DeleteFile_Call) RunAndReturn(run func(ctx context.Context, fileID uuid.UUID, userID uuid.UUID) error) *MockFileService_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadFile provides a mock function for the type MockFileService
func (_mock *MockFileService) DownloadFile(ctx context.Context, fileID uuid.UUID, userID uuid.UUID) (io.ReadCloser, string, int64, error) {
	ret := _mock.Called(ctx, fileID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DownloadFile")
	}

	var r0 io.ReadCloser
	var r1 string
	var r2 int64
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (io.ReadCloser, string, int64, error)); ok {
		return returnFunc(ctx, fileID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) io.ReadCloser); ok {
		r0 = returnFunc(ctx, fileID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) string); ok {
		r1 = returnFunc(ctx, fileID, userID)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID) int64); ok {
		r2 = returnFunc(ctx, fileID, userID)
	} else {
		r2 = ret.Get(2).(int64)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r3 = returnFunc(ctx, fileID, userID)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockFileService_DownloadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadFile'
type MockFileService_DownloadFile_Call struct {
	*mock.Call
}

// DownloadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID uuid.UUID
//   - userID uuid.UUID
func (_e *MockFileService_Expecter) DownloadFile(ctx interface{}, fileID interface{}, userID interface{}) *MockFileService_DownloadFile_Call {
	return &MockFileService_DownloadFile_Call{Call: _e.mock.On("DownloadFile", ctx, fileID, userID)}
}

func (_c *MockFileService_DownloadFile_Call) Run(run func(ctx context.Context, fileID uuid.UUID, userID uuid.UUID)) *MockFileService_DownloadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileService_DownloadFile_Call) Return(reader io.ReadCloser, mimeType string, size int64, err error) *MockFileService_DownloadFile_Call {
	_c.Call.Return(reader, mimeType, size, err)
	return _c
}

func (_c *MockFileService_DownloadFile_Call) RunAndReturn(run func(ctx context.Context, fileID uuid.UUID, userID uuid.UUID) (io.ReadCloser, string, int64, error)) *MockFileService_DownloadFile_Call {
	_c.Call.Return(run)
	return _c
}

// InitUpload provides a mock function for the type MockFileService
func (_mock *MockFileService) InitUpload(ctx context.Context, userID uuid.UUID, name string, mimeType string, size int64, chunksCount int) (model.File, error) {
	ret := _mock.Called(ctx, userID, name, mimeType, size, chunksCount)

	if len(ret) == 0 {
		panic("no return value specified for InitUpload")
	}

	var r0 model.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, int64, int) (model.File, error)); ok {
		return returnFunc(ctx, userID, name, mimeType, size, chunksCount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, int64, int) model.File); ok {
		r0 = returnFunc(ctx, userID, name, mimeType, size, chunksCount)
	} else {
		r0 = ret.Get(0).(model.File)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, int64, int) error); ok {
		r1 = returnFunc(ctx, userID, name, mimeType, size, chunksCount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileService_InitUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitUpload'
type MockFileService_InitUpload_Call struct {
	*mock.Call
}

// InitUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - name string
//   - mimeType string
//   - size int64
//   - chunksCount int
func (_e *MockFileService_Expecter) InitUpload(ctx interface{}, userID interface{}, name interface{}, mimeType interface{}, size interface{}, chunksCount interface{}) *MockFileService_InitUpload_Call {
	return &MockFileService_InitUpload_Call{Call: _e.mock.On("InitUpload", ctx, userID, name, mimeType, size, chunksCount)}
}

func (_c *MockFileService_InitUpload_Call) Run(run func(ctx context.Context, userID uuid.UUID, name string, mimeType string, size int64, chunksCount int)) *MockFileService_InitUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockFileService_InitUpload_Call) Return(file model.File, err error) *MockFileService_InitUpload_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileService_InitUpload_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, name string, mimeType string, size int64, chunksCount int) (model.File, error)) *MockFileService_InitUpload_Call {
	_c.Call.Return(run)
	return _c
}

// UploadChunk provides a mock function for the type MockFileService
func (_mock *MockFileService) UploadChunk(ctx context.Context, fileID uuid.UUID, userID uuid.UUID, chunkIndex int, data []byte) error {
	ret := _mock.Called(ctx, fileID, userID, chunkIndex, data)

	if len(ret) == 0 {
		panic("no return value specified for UploadChunk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, []byte) error); ok {
		r0 = returnFunc(ctx, fileID, userID, chunkIndex, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileService_UploadChunk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadChunk'
type MockFileService_UploadChunk_Call struct {
	*mock.Call
}

// UploadChunk is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID uuid.UUID
//   - userID uuid.UUID
//   - chunkIndex int
//   - data []byte
func (_e *MockFileService_Expecter) UploadChunk(ctx interface{}, fileID interface{}, userID interface{}, chunkIndex interface{}, data interface{}) *MockFileService_UploadChunk_Call {
	return &MockFileService_UploadChunk_Call{Call: _e.mock.On("UploadChunk", ctx, fileID, userID, chunkIndex, data)}
}

func (_c *MockFileService_UploadChunk_Call) Run(run func(ctx context.Context, fileID uuid.UUID, userID uuid.UUID, chunkIndex int, data []byte)) *MockFileService_UploadChunk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 []byte
		if args[4] != nil {
			arg4 = args[4].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockFileService_UploadChunk_Call) Return(err error) *MockFileService_UploadChunk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileService_UploadChunk_Call) RunAndReturn(run func(ctx context.Context, fileID uuid.UUID, userID uuid.UUID, chunkIndex int, data []byte) error) *MockFileService_UploadChunk_Call {
	_c.Call.Return(run)
	return _c
}
