// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/google/uuid"
	"github.com/liebeSonne/gophkeeper/internal/server/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDataService creates a new instance of MockDataService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDataService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDataService {
	mock := &MockDataService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDataService is an autogenerated mock type for the DataService type
type MockDataService struct {
	mock.Mock
}

type MockDataService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDataService) EXPECT() *MockDataService_Expecter {
	return &MockDataService_Expecter{mock: &_m.Mock}
}

// CreateData provides a mock function for the type MockDataService
func (_mock *MockDataService) CreateData(ctx context.Context, userID uuid.UUID, payloadJSON []byte, dataType model.DataType, metadata string) (model.Data, error) {
	ret := _mock.Called(ctx, userID, payloadJSON, dataType, metadata)

	if len(ret) == 0 {
		panic("no return value specified for CreateData")
	}

	var r0 model.Data
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []byte, model.DataType, string) (model.Data, error)); ok {
		return returnFunc(ctx, userID, payloadJSON, dataType, metadata)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []byte, model.DataType, string) model.Data); ok {
		r0 = returnFunc(ctx, userID, payloadJSON, dataType, metadata)
	} else {
		r0 = ret.Get(0).(model.Data)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, []byte, model.DataType, string) error); ok {
		r1 = returnFunc(ctx, userID, payloadJSON, dataType, metadata)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataService_CreateData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateData'
type MockDataService_CreateData_Call struct {
	*mock.Call
}

// CreateData is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - payloadJSON []byte
//   - dataType model.DataType
//   - metadata string
func (_e *MockDataService_Expecter) CreateData(ctx interface{}, userID interface{}, payloadJSON interface{}, dataType interface{}, metadata interface{}) *MockDataService_CreateData_Call {
	return &MockDataService_CreateData_Call{Call: _e.mock.On("CreateData", ctx, userID, payloadJSON, dataType, metadata)}
}

func (_c *MockDataService_CreateData_Call) Run(run func(ctx context.Context, userID uuid.UUID, payloadJSON []byte, dataType model.DataType, metadata string)) *MockDataService_CreateData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 model.DataType
		if args[3] != nil {
			arg3 = args[3].(model.DataType)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockDataService_CreateData_Call) Return(data model.Data, err error) *MockDataService_CreateData_Call {
	_c.Call.Return(data, err)
	return _c
}

func (_c *MockDataService_CreateData_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, payloadJSON []byte, dataType model.DataType, metadata string) (model.Data, error)) *MockDataService_CreateData_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteData provides a mock function for the type MockDataService
func (_mock *MockDataService) DeleteData(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDataService_DeleteData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteData'
type MockDataService_DeleteData_Call struct {
	*mock.Call
}

// DeleteData is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockDataService_Expecter) DeleteData(ctx interface{}, id interface{}, userID interface{}) *MockDataService_DeleteData_Call {
	return &MockDataService_DeleteData_Call{Call: _e.mock.On("DeleteData", ctx, id, userID)}
}

func (_c *MockDataService_DeleteData_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockDataService_DeleteData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDataService_DeleteData_Call) Return(err error) *MockDataService_DeleteData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDataService_DeleteData_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockDataService_DeleteData_Call {
	_c.Call.Return(run)
	return _c
}

// GetData provides a mock function for the type MockDataService
func (_mock *MockDataService) GetData(ctx context.Context, id uuid.UUID, userID uuid.UUID) (model.Data, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetData")
	}

	var r0 model.Data
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (model.Data, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) model.Data); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(model.Data)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataService_GetData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetData'
type MockDataService_GetData_Call struct {
	*mock.Call
}

// GetData is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockDataService_Expecter) GetData(ctx interface{}, id interface{}, userID interface{}) *MockDataService_GetData_Call {
	return &MockDataService_GetData_Call{Call: _e.mock.On("GetData", ctx, id, userID)}
}

func (_c *MockDataService_GetData_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockDataService_GetData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDataService_GetData_Call) Return(data model.Data, err error) *MockDataService_GetData_Call {
	_c.Call.Return(data, err)
	return _c
}

func (_c *MockDataService_GetData_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (model.Data, error)) *MockDataService_GetData_Call {
	_c.Call.Return(run)
	return _c
}

// ListData provides a mock function for the type MockDataService
func (_mock *MockDataService) ListData(ctx context.Context, userID uuid.UUID, page int, pageSize int, dataTypes []model.DataType, query *string) ([]model.Data, int, error) {
	ret := _mock.Called(ctx, userID, page, pageSize, dataTypes, query)

	if len(ret) == 0 {
		panic("no return value specified for ListData")
	}

	var r0 []model.Data
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, []model.DataType, *string) ([]model.Data, int, error)); ok {
		return returnFunc(ctx, userID, page, pageSize, dataTypes, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, []model.DataType, *string) []model.Data); ok {
		r0 = returnFunc(ctx, userID, page, pageSize, dataTypes, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Data)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int, []model.DataType, *string) int); ok {
		r1 = returnFunc(ctx, userID, page, pageSize, dataTypes, query)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int, []model.DataType, *string) error); ok {
		r2 = returnFunc(ctx, userID, page, pageSize, dataTypes, query)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockDataService_ListData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListData'
type MockDataService_ListData_Call struct {
	*mock.Call
}

// ListData is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - page int
//   - pageSize int
//   - dataTypes []model.DataType
//   - query *string
func (_e *MockDataService_Expecter) ListData(ctx interface{}, userID interface{}, page interface{}, pageSize interface{}, dataTypes interface{}, query interface{}) *MockDataService_ListData_Call {
	return &MockDataService_ListData_Call{Call: _e.mock.On("ListData", ctx, userID, page, pageSize, dataTypes, query)}
}

func (_c *MockDataService_ListData_Call) Run(run func(ctx context.Context, userID uuid.UUID, page int, pageSize int, dataTypes []model.DataType, query *string)) *MockDataService_ListData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 []model.DataType
		if args[4] != nil {
			arg4 = args[4].([]model.DataType)
		}
		var arg5 *string
		if args[5] != nil {
			arg5 = args[5].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockDataService_ListData_Call) Return(datas []model.Data, n int, err error) *MockDataService_ListData_Call {
	_c.Call.Return(datas, n, err)
	return _c
}

func (_c *MockDataService_ListData_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, page int, pageSize int, dataTypes []model.DataType, query *string) ([]model.Data, int, error)) *MockDataService_ListData_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateData provides a mock function for the type MockDataService
func (_mock *MockDataService) UpdateData(ctx context.Context, id uuid.UUID, userID uuid.UUID, payloadJSON []byte, dataType model.DataType, metadata string) (model.Data, error) {
	ret := _mock.Called(ctx, id, userID, payloadJSON, dataType, metadata)

	if len(ret) == 0 {
		panic("no return value specified for UpdateData")
	}

	var r0 model.Data
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, []byte, model.DataType, string) (model.Data, error)); ok {
		return returnFunc(ctx, id, userID, payloadJSON, dataType, metadata)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, []byte, model.DataType, string) model.Data); ok {
		r0 = returnFunc(ctx, id, userID, payloadJSON, dataType, metadata)
	} else {
		r0 = ret.Get(0).(model.Data)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, []byte, model.DataType, string) error); ok {
		r1 = returnFunc(ctx, id, userID, payloadJSON, dataType, metadata)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataService_UpdateData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateData'
type MockDataService_UpdateData_Call struct {
	*mock.Call
}

// UpdateData is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
//   - payloadJSON []byte
//   - dataType model.DataType
//   - metadata string
func (_e *MockDataService_Expecter) UpdateData(ctx interface{}, id interface{}, userID interface{}, payloadJSON interface{}, dataType interface{}, metadata interface{}) *MockDataService_UpdateData_Call {
	return &MockDataService_UpdateData_Call{Call: _e.mock.On("UpdateData", ctx, id, userID, payloadJSON, dataType, metadata)}
}

func (_c *MockDataService_UpdateData_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, payloadJSON []byte, dataType model.DataType, metadata string)) *MockDataService_UpdateData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		var arg4 model.DataType
		if args[4] != nil {
			arg4 = args[4].(model.DataType)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockDataService_UpdateData_Call) Return(data model.Data, err error) *MockDataService_UpdateData_Call {
	_c.Call.Return(data, err)
	return _c
}

func (_c *MockDataService_UpdateData_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, payloadJSON []byte, dataType model.DataType, metadata string) (model.Data, error)) *MockDataService_UpdateData_Call {
	_c.Call.Return(run)
	return _c
}
