// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/google/uuid"
	"github.com/liebeSonne/gophkeeper/internal/server/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// GetUserIDFromToken provides a mock function for the type MockAuthService
func (_mock *MockAuthService) GetUserIDFromToken(tokenString string) (uuid.UUID, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for GetUserIDFromToken")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (uuid.UUID, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) uuid.UUID); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_GetUserIDFromToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserIDFromToken'
type MockAuthService_GetUserIDFromToken_Call struct {
	*mock.Call
}

// GetUserIDFromToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockAuthService_Expecter) GetUserIDFromToken(tokenString interface{}) *MockAuthService_GetUserIDFromToken_Call {
	return &MockAuthService_GetUserIDFromToken_Call{Call: _e.mock.On("GetUserIDFromToken", tokenString)}
}

func (_c *MockAuthService_GetUserIDFromToken_Call) Run(run func(tokenString string)) *MockAuthService_GetUserIDFromToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_GetUserIDFromToken_Call) Return(uUID uuid.UUID, err error) *MockAuthService_GetUserIDFromToken_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockAuthService_GetUserIDFromToken_Call) RunAndReturn(run func(tokenString string) (uuid.UUID, error)) *MockAuthService_GetUserIDFromToken_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(ctx context.Context, login string, password string) (model.Token, error) {
	ret := _mock.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 model.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.Token, error)); ok {
		return returnFunc(ctx, login, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.Token); ok {
		r0 = returnFunc(ctx, login, password)
	} else {
		r0 = ret.Get(0).(model.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, login, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *MockAuthService_Expecter) Login(ctx interface{}, login interface{}, password interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, login, password)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, login string, password string)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(token model.Token, err error) *MockAuthService_Login_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(ctx context.Context, login string, password string) (model.Token, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type MockAuthService
func (_mock *MockAuthService) RefreshToken(ctx context.Context, refreshToken string) (model.Token, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 model.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Token, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Token); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(model.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockAuthService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthService_Expecter) RefreshToken(ctx interface{}, refreshToken interface{}) *MockAuthService_RefreshToken_Call {
	return &MockAuthService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *MockAuthService_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_RefreshToken_Call) Return(token model.Token, err error) *MockAuthService_RefreshToken_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockAuthService_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (model.Token, error)) *MockAuthService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Register(ctx context.Context, login string, password string) (model.Token, error) {
	ret := _mock.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 model.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.Token, error)); ok {
		return returnFunc(ctx, login, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.Token); ok {
		r0 = returnFunc(ctx, login, password)
	} else {
		r0 = ret.Get(0).(model.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, login, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *MockAuthService_Expecter) Register(ctx interface{}, login interface{}, password interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, login, password)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, login string, password string)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(token model.Token, err error) *MockAuthService_Register_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(ctx context.Context, login string, password string) (model.Token, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function for the type MockAuthService
func (_mock *MockAuthService) RevokeToken(ctx context.Context, refreshToken string) error {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type MockAuthService_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthService_Expecter) RevokeToken(ctx interface{}, refreshToken interface{}) *MockAuthService_RevokeToken_Call {
	return &MockAuthService_RevokeToken_Call{Call: _e.mock.On("RevokeToken", ctx, refreshToken)}
}

func (_c *MockAuthService_RevokeToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthService_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_RevokeToken_Call) Return(err error) *MockAuthService_RevokeToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_RevokeToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) error) *MockAuthService_RevokeToken_Call {
	_c.Call.Return(run)
	return _c
}
